# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
 # - 3.4
 # - 2.7


install:
- pip install --upgrade numpy coverage pytest pytest-cov codecov
- python setup.py install
#env: NUMBA_DISABLE_JIT=1
script:
- python -m pytest -vv --cov={{ cookiecutter.project_slug }}/
#- codecov --token=

  
{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
{%- endif %}
